### PR TITLE
Simple fix for handling slash in column names

### LINKED ISSUE #105: Slashes in TTYPEn are not handled
Hi,

While trying to read a bunch of FITS files, it fails complaining they have duplicated column names, as it cuts the column name to the value before the slash. An extract of the header:

```
TTYPE8  = 'lsst/u_MEAN'                                                         
TFORM8  = 'E       '                                                            
TTYPE9  = 'lsst/g_MEAN'                                                         
TFORM9  = 'E       '                                                            
TTYPE13 = 'euclid/VIS_MEAN'                                                     
TFORM13 = 'E       '                                                            
TTYPE14 = 'euclid/Y_MEAN'                                                       
TFORM14 = 'E       '                                                            
```
The binary table extension documentation, for the TTYPEn keyword states:

> The value field for this indexed keyword shall contain a  character string, giving the name of field n. It is recommended that only letters, digits, and underscore (hexadecimal code 5F, ``_'') be used in the name. String comparisons with the values of TTYPEn keywords should not be case sensitive. The use of identical names for different fields should be avoided.

So slashes are not recommended, but also neither excluded nor forbidden :)

### PR DESCRIPTION
**Pull request by JulienPeloton**
Closes #105 

This PR is a small fix to allow slash in column name:

```python
In [1]: df = spark.read.format('fits').option('hdu', 1).load('src/test/ressources/colnames_with_slash.fits')
In [2]: df.printSchema()
root
 |-- lsst/u_MEAN: float (nullable = true)
 |-- lsst/g_MEAN: float (nullable = true)
 |-- euclid/VIS_MEAN: float (nullable = true)
 |-- euclid/Y_MEAN: float (nullable = true)
```

Note that the fix is not robust against very exotic column names -- but it should work for header produced by civilised software. Below is the current implementation, versus what should be done in an ideal world.

```scala
/**
    * Decompose each line of the header into (key, value).
    * Note the white space before the slash to include colnames with slash:
    *   a=toto/tutu    / a comment
    * TTYPEn would be `toto/tutu`
    *
    * I reckon This is not very robust though as rows such as
    *   a=toto /tutu    / a comment
    * where the value of TTYPEn is expected to be `toto / tutu` would not
    * be considered, and it would return only `toto`.
    *
    *
    * @param header : (Array[String])
    *   The header of the HDU.
    * @return (Map[String, String]), map array with (keys, values).
    *
    */
  def parseHeader(header : Array[String]) : Map[String, String] = {
    header.map(x => x.split("="))
      .filter(x => x.size > 1)
      .map(x => (x(0).trim(), x(1).split(" /")(0).trim()))
      .toMap
  }

  /**
    * This is a better code than above, but it does not work if
    * there is no comment section on the card...
    *   a=toto/tutu    / a comment --> OK
    *   a=toto/tutu                --> NOT OK
    * Unfortunately, both exist :-(
    *
    * @param header : (Array[String])
    *   The header of the HDU.
    * @return (Map[String, String]), map array with (keys, values).
    *
    */
  def parseHeader_(header : Array[String]) : Map[String, String] = {
    header.map(x => x.split("="))
      .filter(x => x.size > 1)
      .map{x =>
        val head = x(0).trim()
        val ttype_ = x(1).split("/").map(y => y.trim())
  
        val ttype = ttype_.slice(0, ttype_.size - 1).mkString("/")
  
        (head, ttype)
      }.toMap
  }
```

### CODE REVIEW

**Comment by JulienPeloton** [comment]
@ptallada could you test with the code on this branch to see if you can read correctly your files now? just clone the repo, go to the branch, and compile

```bash
# assuming scala 2.11
sbt ++2.11.8 package
# long log
[info] Packaging /path/to/spark-fits/target/scala-2.11/spark-fits_2.11-0.9.0.jar ...
[info] Done packaging.
```

then test the jar by passing it to spark with the `--jars` option (do not forget to remove it from `--packages`).

**Comment by JulienPeloton** [comment]
@ptallada -- did you have time to test the change?

**Comment by ptallada** [comment]
Hi @JulienPeloton,

I'm sorry, I have been very busy and have not had the time to test it yet :/
Also, I've ever compiled anything using scala, so I need to look it up.

It's on my (long) todo list...

**Comment by JulienPeloton** [comment]
Thanks, if you prefer I can make a new release so that you can test more easily (and iterate on another PR if more problems pop up). Let me know.

**Comment by JulienPeloton** [comment]
Hi @ptallada -- I released spark-fits 1.0.0 that contains the fix. Could you test it? It should as simple as specifying the new version:

```
spark-submit [options] --packages com.github.astrolabsoftware:spark-fits_2.11:1.0.0
```

**Comment by ptallada** [comment]
Hi @JulienPeloton,

It did work perfect!

Thanks :)

**Pull request merged**
