### PR TITLE
Issue 81: discarding empty HDU without failing

### PR DESCRIPTION
**Pull request by JulienPeloton**
This PR includes new code that allows to discard empty files when reading a set of files.

Caveats:
- The code will still crash if the first file of the glob is empty (because it is used by default to set initial parameters). For the future!
- with this fix, the check is done at the level of the executor (no real extra latency) - but it will sometimes produce not-so-detailed error (especially if the user is mixing empty and malformed HDUs). For the future!

### CODE REVIEW

**Comment by JulienPeloton** [comment]
@jacobic here is a quick fix for #81. Can you test it by pulling this branch, and let me know if that solve your problem?

I still have to figure out why one of the test is failing on the CI (but working on my laptop...)

**Comment by jacobic** [comment]
Hi @JulienPeloton ,

I tested things with the test files in `src/test/resources/dirImg` (with `hdu=2`). I tested the following cases:

Before fix:
-  no mode option, `df.show()` -> `java.lang.ArrayIndexOutOfBoundsException: 0`
After fix:
- `mode=PERMISSIVE`, `df.show()` -> No exception
- `mode=FAILFAST`, `df.show()` -> `java.lang.ArrayIndexOutOfBoundsException: 0`

This seemed very promising, so I tested the following scenarios with a wildcard that matches the files referenced in #81 and all the other good files (with `hdu=1`):

Before fix:
- no mode option, `df.show()` -> No exception
- no mode option , `df.groupby(...).agg(...)` -> `java.lang.ArrayIndexOutOfBoundsException: 0`

After fix:
- `mode=PERMISSIVE`, `df.show()` -> No exception
- `mode=FAILFAST`, `df.show()` -> No exception
- `mode=PERMISSIVE`, `df.groupby(...).agg(...)` -> `java.lang.ArrayIndexOutOfBoundsException: 0` 
- `mode=FAILFAST`, `df.groupby(...).agg(...)` -> `java.lang.ArrayIndexOutOfBoundsException: 0`

I assume that when I do a `df.show()` for my large glob expression the bad files are not read but in a shuffle they are and that there must be a subtle difference in the file formats of the `src/test/resources/dirImg` files when compared to my files referenced in #81 which prevents the fix from generalising. 

Please note the exception is the same as #81 
```
java.lang.ArrayIndexOutOfBoundsException: 0                                                                                                                                                        at com.astrolabsoftware.sparkfits.FitsHduImage$ImageHDU.getSizeRowBytes(FitsHduImage.scala:77)
at ...
at ...
```

Please let me know if you have any questions or if there is anything else I can do to help :)

Cheers,
Jacob

**Comment by JulienPeloton** [comment]
Hum, too bad :-( Do you see the same error happening for a simple `df.count()`? 

I suspect the error is still happening because when spark-fits initialises parameters, it does a glob on the files, opens the first file, and read header from it. I will inspect that.

**Comment by JulienPeloton** [comment]
And could you paste the error log also with the fix (I would need to see the files and line numbers)?

**Comment by jacobic** [comment]
Hi @JulienPeloton 

Thanks for all your work on this! Here is the full log of the following code sample (with `hdu=1`, `mode=PERMISSIVE`, `verbose=True` and glob expression '10[0-4][0-9]/[0-6]/photoObj-*.fits'):

Screenshot 2019-05-24 at 20 11 32

[slurm-8244078_1.out.txt](https://github.com/astrolabsoftware/spark-fits/files/3218140/slurm-8244078_1.out.txt)

`grep -e julien slurm-8244078_1.out` returns "@julien: show works fine" 

and the same error occurs as before with the count (and therefore there is no second print statement).

Cheers,
Jacob

**Comment by JulienPeloton** [comment]
Thanks @jacobic for the detailed feedback, it is super appreciated :-)

I think I found the error, and fix it. Actually, the error was happening only when both `mode` and `recordlength` options were used (in my test, I was never combining both, but you have to do it due to large row size). And when `recordlength` is set, the code (FitsLib.scala#L191) tries to compare its value to the row size (and an empty HDU has no dimension)... hence the exception.

Could you pull the latest commit and see if the exception is still there?

**Comment by jacobic** [comment]
Works like a charm! 

Time to crack open the beer. Have a nice weekend!

Cheers,
Jacob

**Comment by JulienPeloton** [comment]
Hooray :-) 

Enjoy the weekend too, and I will publish a new release early next week.

**Pull request merged**
